apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-user-auth
  namespace: flux-system
spec:
  encryptedData:
    password: AgCGLAE+iIgIZpi5qlBIoWQpcsXfTSzAk2QKM0MzxISGdzDz/OvBpYJxqKArDP8ARi8Ov0/bTzjOth6yckAvrwt8Ol7OTKCMPPkOMCLot8MVZmN8FVGnUTJj3XjkAGMU0b8cNOZSSwfGGDBQFPMz1B66mQ4Sl2xIjvpliAhxij5t8WWPXuaGs5PAdC6X4pNTcQXz0PWQBnvUHdsjVR0WBYjLP0HwHrD+IMz9rUF8dpwm9CrXLJqGORhcDlCg5LCMiU+Yy868BBPaozHkqYyy6KcNMyBu8MAnU1/yRPRP4oqR/Ks3uU7sOM1ve8aTML9VoABEBkmoiZVb94lm20iHt4755t9LG0Eeqm0Pd8aD+NXzgxX5u0zrUci4+Ly67Y31QSn65FOiRt+Kv20bAJd6GcvEhIwV9zrJa2GxjyWF9eyDfTp21wBUaIJSNS3JDZlTicLV11TT9Rf33anRFSvt+UumczzBvcq6CiGuKnxvJQblz/1aMANWuVab3p1U0BRi/Qv/cOnrKdRrWofzZyf1I65duxlZVF9YX+bs67fMHRywlO2mSvhHjtAzceP+vuiOEb9+M1wRb7BVVVqCBTmw0wRknIMrxzUG+OxK1e87hg30Fd0lFUkGi1r98G2RE6Tkto98i8DiMLb0Q8NK8dmJs56VE1ZLDSMGb4NFupu60AntB6YHuoPkp3iYmsrx9vr3u89JthypN2VpSaPAN0eAoc6a61ENEtqE7tUAPYRX7dvoYoS6HfOWpv7be8jz270uaA18SRNL3QZtw5vwcnk=
    username: AgAeL0XK4R2jbYnswoJeBynls7gNXjiIoWpKgMKOwl9sVdaLRlC5vweK6AG5tDIYJXx+YAILdwte1JY0sId6mutDuTjD89ARgvtfHJtHu9pBgt0inqHUmcNeIm4+Jdx+NX0XinKzbN3PL6f6fZkBI4c3oHp0KjW6DqH8gbCYNifgOzxFGsQRYMchq53dV4yIWYP8nNrPDdzZNFyDMZ1wRvPtg64yQ3XgILOY3PTn2Wd1FlF+q/ER2BMHy9O/xmE/HoFn8+buAZQtpku9eyqclCpoiVapwpcC+bNOg8jR+nu5Xv7M+BYKpUrE8Kbnbpxkl9aOYKDV1xee89aHog4fzG5DkDnv9KDNGBS/bFfwy0v8T8f6MmEx2vx1eZ+1RNO+gnCMqJDDu/rADHcFpXt48hl70pMwg9bUlLV1Mq8RXNFaAMINCYCKkqDDuPCQr/julq1uv9fkjbHMaAzIt63nkNxGa+rtUumIm1AOsedkJd6lY0YIUPGeG46AB9yFJFZ3NI/aHvGQRQHnxcogPrmsB08Tl6c+m/iuUyl3latpRkYXUt4pIhziD+PDs8sExDOUHnChVPinTmthu+frMjIcqUSgQ+5Vjsuvrvh+lK8S0MPgOn5uXkW13OZfTpx/56WPZlE0SC083XuFfO/fh15qtoap8TcYVcQDZe1MZZ6G21t2CLKnAOWViBVwB1EbG9vktIgOtXoOgLKvG6Dp
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cluster-user-auth
      namespace: flux-system

